### ISSUE TITLE
Readme is not updated

### ISSUE THREAD

**Issue by HarelM** [oscarfonts/mapbox-gl-cordova-offline#40]
Is the following line in the readme file up-to-date?
>Use the bundled library from www/mapbox-gl-cordova-offline.js which is based in mapbox-gl-js v.0.44.0, or install it as npm

Also, I was wondering if there's another way to create an offline mbtiles layer without creating a special version of mapbox?

I'm looking into solving this for an app i'm writing and I would like to use the official mapbox-gl package alongside this one...
I'd love to help out in any way that I can...

**Comment by michogar** [comment]
Hi, 

sorry about the README, this is an error because the last Mapbox version supported is the 0.53.1 version. It will be fixed in the next feature added.

The version that we are working with the offline library is the original Mapbox version. No changes are needed, we only add new features over the original so you can use the official mapbox version.
